<?php
$root=__DIR__;$checks=[];$phpOk=version_compare(PHP_VERSION,'8.1.0','>=');$pdoOk=extension_loaded('pdo_mysql');$finfoOk=extension_loaded('fileinfo');
$checks[]=['PHP >= 8.1',$phpOk,PHP_VERSION];$checks[]=['PDO MySQL',$pdoOk,$pdoOk?'พร้อม':'กรุณาเปิด extension pdo_mysql'];$checks[]=['Fileinfo',$finfoOk,$finfoOk?'พร้อม':'กรุณาเปิด extension fileinfo'];
$dbOk=false;$dbDetail='ยังไม่ได้ตรวจ';
if($pdoOk){try{$c=require $root.'/config/database.php';$pdo=new PDO(sprintf('mysql:host=%s;port=%s;dbname=%s;charset=%s',$c['host'],$c['port'],$c['name'],$c['charset']),$c['user'],$c['pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$st=$pdo->query("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='tbl_member'");$dbOk=(int)$st->fetchColumn()===1;$dbDetail=$dbOk?'เชื่อมต่อ equiptrack_db สำเร็จ':'เชื่อมต่อได้ แต่ยังไม่ได้ Import equiptrack_db.sql';}catch(Throwable $e){$dbDetail=$e->getMessage();}}
$checks[]=['ฐานข้อมูล',$dbOk,$dbDetail];
foreach(['uploads/devices','uploads/members'] as $dir){$path=$root.'/'.$dir;$ok=is_dir($path)&&is_writable($path);$checks[]=[$dir,$ok,$ok?'เขียนไฟล์ได้':(is_dir($path)?'ไม่มีสิทธิ์เขียน':'ไม่พบโฟลเดอร์')];}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EquipTrack System Check</title><style>body{margin:0;background:#f5f7fb;color:#172033;font-family:Tahoma,system-ui,sans-serif}.wrap{max-width:760px;margin:50px auto;padding:20px}.card{background:#fff;border:1px solid #e5eaf1;border-radius:20px;box-shadow:0 18px 50px #0f172a12;overflow:hidden}.head{padding:22px 24px;border-bottom:1px solid #e5eaf1}.head h1{margin:0;font-size:22px}.head p{margin:4px 0 0;color:#667085}.list{padding:8px 24px}.row{display:grid;grid-template-columns:40px 180px 1fr;gap:12px;align-items:center;padding:14px 0;border-bottom:1px solid #eef1f5}.row:last-child{border:0}.icon{width:34px;height:34px;border-radius:10px;display:grid;place-items:center;font-weight:bold}.ok{background:#ecfdf3;color:#15803d}.no{background:#fff1f0;color:#b42318}.name{font-weight:bold}.detail{color:#667085;font-size:12px;word-break:break-word}.foot{padding:18px 24px;border-top:1px solid #e5eaf1;display:flex;gap:10px}.btn{display:inline-block;background:#2563eb;color:#fff;padding:10px 15px;border-radius:10px;text-decoration:none}.btn2{background:#fff;color:#344054;border:1px solid #d7dfeb}@media(max-width:600px){.row{grid-template-columns:38px 1fr}.detail{grid-column:2}}</style></head><body><div class="wrap"><div class="card"><div class="head"><h1>EquipTrack System Check</h1><p>Native PHP + MySQL • ไม่ใช้ CodeIgniter</p></div><div class="list"><?php foreach($checks as [$name,$ok,$detail]):?><div class="row"><span class="icon <?=$ok?'ok':'no'?>"><?=$ok?'✓':'!'?></span><span class="name"><?=h($name)?></span><span class="detail"><?=h($detail)?></span></div><?php endforeach;?></div><div class="foot"><a class="btn" href="./">เปิด EquipTrack</a><a class="btn btn2" href="http://localhost/phpmyadmin/">เปิด phpMyAdmin</a></div></div></div></body></html>
