<?php
require dirname(__DIR__).'/includes/bootstrap.php';require_staff_or_admin();
$ds=trim((string)($_GET['ds']??''));$de=trim((string)($_GET['de']??''));$type=(int)($_GET['type']??0);$member=(int)($_GET['member']??0);$status=trim((string)($_GET['status']??''));
$allowedStatuses=['pending','approved','borrowed','rejected','cancelled','returned'];if(!in_array($status,$allowedStatuses,true))$status='';
$validDate=fn($d)=>$d===''||(($x=DateTime::createFromFormat('Y-m-d',$d))&&$x->format('Y-m-d')===$d);if(!$validDate($ds))$ds='';if(!$validDate($de))$de='';
$where=[];$params=[];if($ds!==''){$where[]='DATE(s.ser_datesave)>=?';$params[]=$ds;}if($de!==''){$where[]='DATE(s.ser_datesave)<=?';$params[]=$de;}if($type){$where[]='s.ref_t_id=?';$params[]=$type;}if($member){$where[]='s.ref_m_id=?';$params[]=$member;}if($status!==''){$where[]='s.ser_status=?';$params[]=$status;}
$sql="SELECT s.*,m.m_fname,m.m_name,m.m_lname,m.m_email,d.d_name,d.d_id,t.t_name FROM tbl_devices_service s JOIN tbl_member m ON m.m_id=s.ref_m_id JOIN tbl_devices d ON d.d_id=s.ref_d_id LEFT JOIN tbl_devices_type t ON t.t_id=s.ref_t_id".($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY s.ser_id DESC';$rows=fetch_all($sql,$params);
if(($_GET['export']??'')==='csv'){
 header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="equiptrack_report_'.date('Ymd_His').'.csv"');echo "\xEF\xBB\xBF";$out=fopen('php://output','w');fputcsv($out,['ID','รหัสครุภัณฑ์','ชื่อครุภัณฑ์','ประเภท','ผู้ยืม','วัตถุประสงค์','สถานะ','วันที่ยืม','วันที่คืน']);foreach($rows as $r){[$label]=status_label($r['ser_status']);fputcsv($out,[$r['ser_id'],$r['d_id'],$r['d_name'],$r['t_name'],full_name($r),$r['ser_reason'],$label,$r['ser_date_lend'],$r['ser_date_return']]);}fclose($out);exit;
}
$types=fetch_all('SELECT * FROM tbl_devices_type ORDER BY t_name');$members=fetch_all('SELECT m_id,m_fname,m_name,m_lname FROM tbl_member WHERE ref_pid NOT IN (1,3) ORDER BY m_name,m_lname');
$statusCounts=[];$typeCounts=[];foreach($rows as $r){$statusCounts[$r['ser_status']]=($statusCounts[$r['ser_status']]??0)+1;$typeCounts[$r['t_name']?:'ไม่ระบุ']=($typeCounts[$r['t_name']?:'ไม่ระบุ']??0)+1;}$maxType=$typeCounts?max($typeCounts):1;
$total=count($rows);$returned=$statusCounts['returned']??0;$active=($statusCounts['approved']??0)+($statusCounts['borrowed']??0);$pending=$statusCounts['pending']??0;
$query=$_GET;unset($query['export']);$exportUrl='reports/index.php?'.http_build_query(array_merge($query,['export'=>'csv']));render_header('รายงานการยืม–คืน','reports');
?>
<div class="page-intro"><div><h2>รายงานและสถิติ</h2><p>กรองข้อมูลตามช่วงวันที่ ประเภท ผู้ยืม และสถานะ พร้อม Export CSV ได้ทันที</p></div><div class="actions"><a class="btn btn-soft" href="<?=e(url($exportUrl))?>">Export CSV</a><button class="btn btn-soft" onclick="window.print()">พิมพ์รายงาน</button></div></div>
<div class="card no-print"><div class="card-body"><form method="get" class="filter-bar"><div class="form-group"><label>วันที่เริ่ม</label><input class="form-control" type="date" name="ds" value="<?=e($ds)?>"></div><div class="form-group"><label>วันที่สิ้นสุด</label><input class="form-control" type="date" name="de" value="<?=e($de)?>"></div><div class="form-group"><label>ประเภท</label><select class="form-control" name="type"><option value="0">ทั้งหมด</option><?php foreach($types as $t):?><option value="<?=e($t['t_id'])?>" <?=$type===(int)$t['t_id']?'selected':''?>><?=e($t['t_name'])?></option><?php endforeach;?></select></div><div class="form-group"><label>ผู้ยืม</label><select class="form-control" name="member"><option value="0">ทั้งหมด</option><?php foreach($members as $m):?><option value="<?=e($m['m_id'])?>" <?=$member===(int)$m['m_id']?'selected':''?>><?=e(full_name($m))?></option><?php endforeach;?></select></div><div class="form-group"><label>สถานะ</label><select class="form-control" name="status"><option value="">ทั้งหมด</option><?php foreach($allowedStatuses as $s):[$lab]=status_label($s);?><option value="<?=e($s)?>" <?=$status===$s?'selected':''?>><?=e($lab)?></option><?php endforeach;?></select></div><button class="btn btn-primary" type="submit">กรองข้อมูล</button><a class="btn btn-soft" href="<?=e(url('reports/index.php'))?>">ล้าง</a></form></div></div>
<div class="grid grid-4 mt-2"><div class="card stat-card"><span class="stat-icon">▤</span><div class="stat-info"><small>ทั้งหมด</small><strong><?=$total?></strong><span>ตามตัวกรอง</span></div></div><div class="card stat-card"><span class="stat-icon orange">◷</span><div class="stat-info"><small>รออนุมัติ</small><strong><?=$pending?></strong><span>รายการ</span></div></div><div class="card stat-card"><span class="stat-icon">↗</span><div class="stat-info"><small>กำลังยืม</small><strong><?=$active?></strong><span>รายการ</span></div></div><div class="card stat-card"><span class="stat-icon green">✓</span><div class="stat-info"><small>คืนแล้ว</small><strong><?=$returned?></strong><span>รายการ</span></div></div></div>
<div class="grid grid-3 mt-2"><div class="card"><div class="card-header"><div><h3>การใช้งานตามประเภท</h3><p>จากข้อมูลตามตัวกรองปัจจุบัน</p></div></div><div class="card-body"><div class="chart-bars"><?php if(!$typeCounts):?><div class="empty-state"><h3>ไม่มีข้อมูล</h3></div><?php else:foreach($typeCounts as $name=>$count):?><div class="bar-row"><span class="bar-label" title="<?=e($name)?>"><?=e($name)?></span><div class="bar-track"><div class="bar-fill" style="width:<?=e((string)round($count/$maxType*100,1))?>%"></div></div><b class="bar-value"><?=$count?></b></div><?php endforeach;endif;?></div></div></div><div class="card span-2"><div class="card-header"><div><h3>รายละเอียดรายการ</h3><p>ข้อมูลยืม–คืนทั้งหมดตามตัวกรอง</p></div></div><div class="table-tools no-print"><div class="table-search"><input type="search" placeholder="ค้นหาในรายงาน…" data-table-search="#reportTable"></div><span class="table-meta"><?=$total?> รายการ</span></div><div class="table-wrap"><table class="data-table" id="reportTable"><thead><tr><th>ครุภัณฑ์</th><th>ผู้ยืม</th><th>สถานะ</th><th>วันที่ยืม</th><th>วันที่คืน</th><th>วัตถุประสงค์</th></tr></thead><tbody><?php if(!$rows):?><tr data-empty><td colspan="6"><div class="empty-state"><div class="empty-icon">▤</div><h3>ไม่พบข้อมูลตามตัวกรอง</h3></div></td></tr><?php else:foreach($rows as $r):?><tr><td><b class="cell-title"><?=e($r['d_name'])?></b><small class="cell-sub"><?=e($r['d_id'])?> • <?=e($r['t_name']?:'-')?></small></td><td><?=e(full_name($r))?></td><td><?=badge_service($r['ser_status'])?></td><td><?=e(thai_date($r['ser_date_lend']))?></td><td><?=e(thai_date($r['ser_date_return']))?></td><td><?=e($r['ser_reason'])?></td></tr><?php endforeach;endif;?></tbody></table></div></div></div>
<?php render_footer();?>
