<?php
require dirname(__DIR__).'/includes/bootstrap.php'; require_staff_or_admin();
$no=get_int('no');$row=$no?fetch_one('SELECT * FROM tbl_devices WHERE no=?',[$no]):null;if($no&&!$row)render_error('ไม่พบครุภัณฑ์','รายการที่ต้องการแก้ไขไม่มีอยู่ในระบบ');
$types=fetch_all('SELECT * FROM tbl_devices_type ORDER BY t_name');$statuses=fetch_all('SELECT * FROM tbl_devices_status WHERE s_id<>2 ORDER BY s_id');$errors=[];
$hasActive=$row?(int)scalar("SELECT COUNT(*) FROM tbl_devices_service WHERE ref_d_id=? AND ser_status IN ('approved','borrowed')",[$row['d_id']])>0:false;
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$no=int_post('no');$row=$no?fetch_one('SELECT * FROM tbl_devices WHERE no=?',[$no]):null;
 $code=post('d_id');$name=post('d_name');$type=int_post('ref_t_id');$status=int_post('ref_s_id');$detail=post('d_detail');$remark=post('d_remark');
 $hasActive=$row?(int)scalar("SELECT COUNT(*) FROM tbl_devices_service WHERE ref_d_id=? AND ser_status IN ('approved','borrowed')",[$row['d_id']])>0:false;
 if($code===''||text_len($code)>50)$errors[]='กรุณากรอกรหัสครุภัณฑ์ไม่เกิน 50 ตัวอักษร';if($name==='')$errors[]='กรุณากรอกชื่อครุภัณฑ์';
 if(!(int)scalar('SELECT COUNT(*) FROM tbl_devices_type WHERE t_id=?',[$type]))$errors[]='กรุณาเลือกประเภทครุภัณฑ์';
 if($hasActive)$status=2; elseif(!(int)scalar('SELECT COUNT(*) FROM tbl_devices_status WHERE s_id=? AND s_id<>2',[$status]))$errors[]='กรุณาเลือกสถานะที่ถูกต้อง';
 if((int)scalar('SELECT COUNT(*) FROM tbl_devices WHERE d_id=? AND no<>?',[$code,$no])>0)$errors[]='รหัสครุภัณฑ์นี้มีอยู่แล้ว';
 if(!$errors){try{$img=upload_image('d_img','devices',$row['d_img']??null);if($no){execute_sql('UPDATE tbl_devices SET ref_t_id=?,ref_s_id=?,d_id=?,d_name=?,d_detail=?,d_remark=?,d_img=? WHERE no=?',[$type,$status,$code,$name,$detail,$remark,$img,$no]);flash('success','แก้ไขครุภัณฑ์เรียบร้อย');}else{execute_sql('INSERT INTO tbl_devices(ref_t_id,ref_s_id,d_id,d_name,d_detail,d_remark,d_img,ref_m_id) VALUES(?,?,?,?,?,?,?,?)',[$type,$status,$code,$name,$detail,$remark,$img,current_user()['m_id']]);flash('success','เพิ่มครุภัณฑ์เรียบร้อย');}redirect('staff/devices.php');}catch(Throwable $e){$errors[]=$e->getMessage();}}
}
$v=function($k,$d='')use($row){return $_SERVER['REQUEST_METHOD']==='POST'?($_POST[$k]??$d):($row[$k]??$d);};render_header($no?'แก้ไขครุภัณฑ์':'เพิ่มครุภัณฑ์','devices');
?>
<div class="page-intro"><div><h2><?=$no?'แก้ไขข้อมูลครุภัณฑ์':'เพิ่มครุภัณฑ์ใหม่'?></h2><p>รูปและข้อมูลอุปกรณ์ถูกจัดเก็บแยกจากรูปผู้ใช้งานอย่างชัดเจน</p></div><a class="btn btn-soft" href="<?=e(url('staff/devices.php'))?>">← กลับ</a></div>
<?php if($errors):?><div class="inline-alert danger"><b>!</b><span><?=implode('<br>',array_map('e',$errors))?></span></div><?php endif;?>
<?php if($hasActive):?><div class="inline-alert warning"><b>i</b><span>ครุภัณฑ์นี้กำลังถูกยืม สถานะจะถูกล็อกไว้เป็น “กำลังถูกยืม” จนกว่าจะรับคืน</span></div><?php endif;?>
<form method="post" enctype="multipart/form-data"><?=csrf_field()?><input type="hidden" name="no" value="<?=e($no)?>"><div class="grid grid-3"><div class="card span-2"><div class="card-header"><div><h3>ข้อมูลครุภัณฑ์</h3><p>จัดช่องกรอกเป็นแนวเดียวกันเพื่ออ่านง่าย</p></div></div><div class="card-body"><div class="form-grid"><div class="form-group"><label>รหัสครุภัณฑ์ <span class="required">*</span></label><input class="form-control" name="d_id" maxlength="50" required value="<?=e($v('d_id'))?>" placeholder="เช่น NB-001"></div><div class="form-group"><label>ชื่อครุภัณฑ์ <span class="required">*</span></label><input class="form-control" name="d_name" maxlength="120" required value="<?=e($v('d_name'))?>"></div><div class="form-group"><label>ประเภท <span class="required">*</span></label><select class="form-control" name="ref_t_id" required><option value="">เลือกประเภท</option><?php foreach($types as $t):?><option value="<?=e($t['t_id'])?>" <?=((int)$v('ref_t_id')===(int)$t['t_id']?'selected':'')?>><?=e($t['t_name'])?></option><?php endforeach;?></select></div><div class="form-group"><label>สถานะ</label><?php if($hasActive):?><input type="hidden" name="ref_s_id" value="2"><input class="form-control" value="กำลังถูกยืม" disabled><?php else:?><select class="form-control" name="ref_s_id"><?php foreach($statuses as $s):?><option value="<?=e($s['s_id'])?>" <?=((int)$v('ref_s_id',1)===(int)$s['s_id']?'selected':'')?>><?=e($s['s_name'])?></option><?php endforeach;?></select><?php endif;?></div><div class="form-group full"><label>รายละเอียด</label><textarea class="form-control" name="d_detail" maxlength="2000" placeholder="รายละเอียด รุ่น สเปก หรือข้อมูลที่จำเป็น"><?=e($v('d_detail'))?></textarea></div><div class="form-group full"><label>หมายเหตุ</label><textarea class="form-control" name="d_remark" maxlength="2000" placeholder="หมายเหตุเพิ่มเติม"><?=e($v('d_remark'))?></textarea></div></div></div></div><div class="card"><div class="card-header"><div><h3>รูปครุภัณฑ์</h3><p>ไม่ใช้รูป Staff เป็นรูปสำรอง</p></div></div><div class="card-body"><div class="image-uploader" style="display:block"><div class="image-preview" id="devicePreview" style="width:100%;height:210px;margin-bottom:14px"><?php $pre=$row?device_image($row):'';if($pre):?><img src="<?=e($pre)?>" alt=""><?php else:?>ไม่มีรูป<?php endif;?></div><div class="upload-copy"><b>เลือกรูปใหม่</b><small class="form-help">JPG, PNG, WEBP • ไม่เกิน 5 MB</small><input type="file" name="d_img" accept="image/jpeg,image/png,image/webp" data-preview="#devicePreview"></div></div></div></div></div><div class="form-actions mt-2"><a class="btn btn-soft" href="<?=e(url('staff/devices.php'))?>">ยกเลิก</a><button class="btn btn-primary" type="submit">บันทึกครุภัณฑ์</button></div></form>
<?php render_footer();?>
