<?php
require dirname(__DIR__).'/includes/bootstrap.php'; require ROOT_PATH.'/includes/services.php'; require_staff_or_admin();$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$ids=array_map('strval',(array)($_POST['device']??[]));$member=int_post('ref_m_id');$reason=post('ser_reason');$u=current_user();try{create_direct_loan_tx($ids,$member,$reason,(int)$u['m_id'],full_name($u));flash('success','บันทึกการยืมครุภัณฑ์เรียบร้อย');redirect('staff/loans.php');}catch(Throwable $e){$errors[]=$e->getMessage();}}
$members=fetch_all('SELECT m.m_id,m.m_fname,m.m_name,m.m_lname,m.m_email,p.pname FROM tbl_member m JOIN tbl_position p ON p.pid=m.ref_pid WHERE m.ref_pid NOT IN (1,3) ORDER BY m.m_name,m.m_lname');
$devices=fetch_all("SELECT d.*,t.t_name FROM tbl_devices d JOIN tbl_devices_type t ON t.t_id=d.ref_t_id WHERE d.ref_s_id=1 AND NOT EXISTS(SELECT 1 FROM tbl_devices_service s WHERE s.ref_d_id=d.d_id AND s.ser_status='pending') ORDER BY d.d_name,d.d_id");
render_header('บันทึกการยืม','direct-loan');
?>
<div class="page-intro"><div><h2>บันทึกยืมโดยเจ้าหน้าที่</h2><p>ใช้เมื่อต้องการยืนยันการยืมทันทีโดยไม่ผ่านขั้นตอนคำขอจากผู้ยืม</p></div><a class="btn btn-soft" href="<?=e(url('staff/loans.php'))?>">ดูรายการกำลังยืม</a></div><?php if($errors):?><div class="inline-alert danger"><b>!</b><span><?=implode('<br>',array_map('e',$errors))?></span></div><?php endif;?>
<form method="post"><?=csrf_field()?><div class="card"><div class="card-header"><div><h3>ข้อมูลการยืม</h3><p>เลือกผู้ยืมและครุภัณฑ์ที่พร้อมใช้งาน</p></div></div><div class="card-body"><div class="form-grid"><div class="form-group full"><label>ผู้ยืม <span class="required">*</span></label><select class="form-control" name="ref_m_id" required><option value="">เลือกผู้ยืม</option><?php foreach($members as $m):?><option value="<?=e($m['m_id'])?>" <?=((int)($_POST['ref_m_id']??0)===(int)$m['m_id']?'selected':'')?>><?=e(full_name($m))?> — <?=e($m['pname'])?><?=($m['m_email']?' / '.e($m['m_email']):'')?></option><?php endforeach;?></select></div><div class="form-group full"><label>วัตถุประสงค์ <span class="required">*</span></label><textarea class="form-control" name="ser_reason" maxlength="255" required placeholder="ระบุวัตถุประสงค์ในการยืม"><?=e($_POST['ser_reason']??'')?></textarea></div><div class="form-group full"><label>ครุภัณฑ์ <span class="required">*</span></label><?php if(!$devices):?><div class="inline-alert warning mb-0"><b>i</b><span>ไม่มีครุภัณฑ์ที่พร้อมให้ยืมในขณะนี้</span></div><?php else:?><div class="check-list"><?php foreach($devices as $d):$img=device_image($d);?><label class="check-card"><input type="checkbox" name="device[]" value="<?=e($d['d_id'])?>"><span class="mini-avatar"><?php if($img):?><img src="<?=e($img)?>" alt=""><?php else:?>ET<?php endif;?></span><span><b class="cell-title"><?=e($d['d_name'])?></b><small class="cell-sub"><?=e($d['d_id'])?> • <?=e($d['t_name'])?></small></span></label><?php endforeach;?></div><?php endif;?></div></div></div><div class="card-footer"><div class="form-actions"><a class="btn btn-soft" href="<?=e(url('staff/dashboard.php'))?>">ยกเลิก</a><button class="btn btn-primary" type="submit" <?=$devices?'':'disabled'?>>บันทึกการยืม</button></div></div></div></form>
<?php render_footer();?>
