<?php
require dirname(__DIR__).'/includes/bootstrap.php'; require ROOT_PATH.'/includes/services.php'; require_staff_or_admin();
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$id=int_post('id');$action=post('action');$u=current_user();
 try{if($action==='approve'){approve_request_tx($id,(int)$u['m_id'],full_name($u));flash('success','อนุมัติคำขอยืมเรียบร้อย');}elseif($action==='reject'){reject_request_tx($id,(int)$u['m_id'],full_name($u));flash('success','ปฏิเสธคำขอยืมเรียบร้อย');}}catch(Throwable $e){flash('danger',$e->getMessage());}
 redirect('staff/requests.php');
}
$rows=fetch_all("SELECT s.*,m.m_fname,m.m_name,m.m_lname,m.m_email,m.m_phone,d.d_name,d.d_id,d.d_img,t.t_name FROM tbl_devices_service s JOIN tbl_member m ON m.m_id=s.ref_m_id JOIN tbl_devices d ON d.d_id=s.ref_d_id LEFT JOIN tbl_devices_type t ON t.t_id=s.ref_t_id WHERE s.ser_status='pending' ORDER BY s.ser_request_date ASC,s.ser_id ASC");
render_header('คำขอยืมที่รออนุมัติ','requests');
?>
<div class="page-intro"><div><h2>คำขอยืม</h2><p>ตรวจสอบผู้ยืม วัตถุประสงค์ และครุภัณฑ์ก่อนอนุมัติ ระบบจะล็อกอุปกรณ์ด้วย Transaction เพื่อป้องกันการยืมซ้ำ</p></div><span class="badge badge-warning"><?=count($rows)?> รอดำเนินการ</span></div>
<div class="card"><div class="table-tools"><div class="table-search"><input type="search" placeholder="ค้นหาผู้ยืม หรือครุภัณฑ์…" data-table-search="#requestTable"></div></div><div class="table-wrap"><table class="data-table" id="requestTable"><thead><tr><th>ครุภัณฑ์</th><th>ผู้ยืม</th><th>วัตถุประสงค์</th><th>วันที่ขอ</th><th>จัดการ</th></tr></thead><tbody><?php if(!$rows):?><tr data-empty><td colspan="5"><div class="empty-state"><div class="empty-icon">✓</div><h3>ไม่มีคำขอค้าง</h3><p>คำขอยืมทั้งหมดถูกดำเนินการแล้ว</p></div></td></tr><?php else:foreach($rows as $r):$img=device_image($r);?><tr><td><div class="device-cell"><?php if($img):?><img class="device-thumb" src="<?=e($img)?>" alt=""><?php else:?><span class="device-placeholder">ET</span><?php endif;?><span><b class="cell-title"><?=e($r['d_name'])?></b><small class="cell-sub"><?=e($r['d_id'])?> • <?=e($r['t_name']?:'-')?></small></span></div></td><td><b class="cell-title"><?=e(trim($r['m_fname'].' '.$r['m_name'].' '.$r['m_lname']))?></b><small class="cell-sub"><?=e($r['m_email']?:'-')?> • <?=e($r['m_phone']?:'-')?></small></td><td><?=e($r['ser_reason'])?></td><td class="nowrap"><?=e(thai_date($r['ser_request_date'],true))?></td><td><div class="btn-group"><form method="post" data-confirm="อนุมัติคำขอยืม <?=e($r['d_name'])?> หรือไม่?" data-confirm-title="อนุมัติคำขอ"><?=csrf_field()?><input type="hidden" name="action" value="approve"><input type="hidden" name="id" value="<?=e($r['ser_id'])?>"><button class="btn btn-success btn-sm">อนุมัติ</button></form><form method="post" data-confirm="ปฏิเสธคำขอยืมนี้หรือไม่?" data-confirm-title="ปฏิเสธคำขอ"><?=csrf_field()?><input type="hidden" name="action" value="reject"><input type="hidden" name="id" value="<?=e($r['ser_id'])?>"><button class="btn btn-danger-soft btn-sm">ปฏิเสธ</button></form></div></td></tr><?php endforeach;endif;?></tbody></table></div></div>
<?php render_footer();?>
